	CREATE TABLE sebasbg01_coderhouse.datos_gov_co (
	    Id INTEGER IDENTITY(1,1) PRIMARY KEY,
	    impacto TEXT,
	    circuito TEXT, 
	    servicio TEXT, 
	    motivo TEXT, 
	    solicita TEXT,
	    numeroinstalacion TEXT,
	    municipio TEXT,
	    nombreresponsable TEXT, 
	    fecha_y_hora_esperada TIMESTAMP,
	    inicio TIMESTAMP,
	    fin TIMESTAMP,
	    horas FLOAT, 
	    estado TEXT, 
	    fecharegistro TIMESTAMP,
	    barrio TEXT, 
	    nombrecontratista TEXT,
	    tipoaviso TEXT 
	)
