CREATE TABLE datos_gov_co (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    impacto TEXT,
    circuito TEXT,
    servicio TEXT,
    motivo TEXT,
    solicita TEXT,
    numeroinstalacion TEXT,
    municipio TEXT,
    direccion TEXT,
    nombreresponsable TEXT,
    fecha_y_hora_esperada TIMESTAMP,
    inicio TIMESTAMP,  
    fin TIMESTAMP,  
    horas FLOAT, 
    estado TEXT,
    fecharesgistro TIMESTAMP, 
    explicacion TEXT,
    barrio TEXT,
    nombrecontratista TEXT,
    tipoaviso TEXT)