	CREATE TABLE IF NOT EXISTS sebasbg01_coderhouse.datos_gov_co (
        impacto VARCHAR(250),
        circuito VARCHAR(250),
        servicio VARCHAR(250),
        motivo VARCHAR(250),
        solicita VARCHAR(250),
        numeroinstalacion VARCHAR(250),
        municipio VARCHAR(250),
        nombreresponsable VARCHAR(250),
        fecha_y_hora_esperada TIMESTAMP,
        inicio TIMESTAMP,
        fin TIMESTAMP,
        horas FLOAT,
        estado VARCHAR(250),
        fecharegistro DATE,
        barrio VARCHAR(250),
        nombrecontratista VARCHAR(250),
        tipoaviso VARCHAR(250),
        CONSTRAINT unique_entry UNIQUE (numeroinstalacion, fecharegistro, municipio)
    )
